# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e4349d52c0ec8794f55df990591edc897e7fb7d87fadeb0d99a04cab25f7be7df2f46d7e0275c0d88a23340e152550169d51e684e2618b68eac952e7acfd3c1

test:
  secret_key_base: 22ead8c5ff1dee1f423054f391dbc523440e009fe51cd42f8b00229567fa23372557c14a18a2f799b893cdbcfb29bb3d57902677534ea6606f8df0be743da934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
